module.exports = {
    ADD_NICKNAME: 'ADD_NICKNAME',
    ADD_USER: 'ADD_USER',
    ADD_USER_INITIAL: 'ADD_USER_INITIAL',
    USER_LEAVE: 'USER_LEAVE',
    CONNECT_USER: 'CONNECT_USER',
    DISCONNECT_USER: 'DISCONNECT_USER',
    SEND_MESSAGE: 'SEND_MESSAGE',
    GET_MESSAGE: 'GET_MESSAGE',
}